cache:
  key: "$CI_COMMIT_REF_NAME"
  untracked: true
  paths:
  - node_modules/
  - .yarn/

before_script:
 - yarn config set cache-folder .yarn
 - yarn

lint:
  image: node:latest
  stage: test
  script:
   - npm run lint

build:
  image: node:latest
  stage: build
  script:
   - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  image: go:latest
  stage: deploy
  script:
   - go get github.com/netlify/netlifyctl
   - netlifyctl -y -A $NETLIFY_KEY deploy
