stages:
  - test
  - build

lint:
  image: node:latest
  stage: test
  cache:
    key: "v1-$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
      - .yarn/
  script:
    - yarn config set cache-folder .yarn
    - yarn
    - npm run lint

build:
  image: node:latest
  stage: build
  cache:
    key: "v1-$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
  artifacts:
    expire_in: 3 days
    paths:
      - dist
