stages:
  - test
  - build
  - deploy

lint:
  image: node:lts
  stage: test
  cache:
    key: "v2-$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
      - .yarn/
  before_script:
    - yarn config set cache-folder .yarn
    - yarn
  script:
    - yarn lint

build:
  image: node:lts
  stage: build
  cache:
    key: "v2-$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
      - .yarn/
    policy: pull
  before_script:
    - yarn config set cache-folder .yarn
    - yarn
  script:
    - yarn build
    - if [ ! -d dist/ ]; then exit 1; fi
  artifacts:
    expire_in: 3 days
    paths:
      - dist
  except:
    - live

deploy_master:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add --no-cache curl
  script:
    - curl -X POST -d '' https://api.netlify.com/build_hooks/$NETLIFY_MASTER
  only:
    - master
