test:js:
  image: node:latest
  cache:
    paths:
    - node_modules/
    - .yarn/
  before_script:
   - npm install yarn
   - yarn
   - yarn config set cache-folder .yarn
  script:
   - npm run lint
