stages:
  - test
  - build

lint:
  image: node:lts
  stage: test
  cache:
    key: "v5-$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
  before_script:
    - yarn
  script:
    - yarn lint

build:
  image: node:lts
  stage: build
  cache:
    key: "v5-$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
    policy: pull
  before_script:
    - yarn
  script:
    - yarn build
    - if [ ! -d dist/ ]; then exit 1; fi
  artifacts:
    expire_in: 3 days
    paths:
      - dist
  except:
    - live
