cache:
  paths:
    - node_modules/
    - .yarn/

stages:
  - test
  - build
  - deploy

lint:
  image: node:latest
  stage: test
  script:
    - yarn config set cache-folder .yarn
    - yarn
    - npm run lint

build:
  image: node:latest
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  image: golang:latest
  stage: deploy
  only:
    refs:
      - live
      - test-ci
  script:
    - go get github.com/netlify/netlifyctl
    - netlifyctl -y -A $NETLIFY_KEY deploy
