stages:
  - test
  - build
  - deploy

lint:
  image: node:latest
  stage: test
  cache:
    paths:
      - node_modules/
      - .yarn/
  script:
    - yarn config set cache-folder .yarn
    - yarn
    - npm run lint

build:
  image: node:latest
  stage: build
  except:
    - master
  cache:
    paths:
      - node_modules/
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  image: golang:latest
  stage: deploy
  only:
    - live
  script:
    - go get github.com/netlify/netlifyctl
    - netlifyctl -y -A $NETLIFY_KEY deploy
