stages:
  - test
  - build
  - deploy

lint:
  image: node:latest
  stage: test
  cache:
    key: "v2-$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
      - .yarn/
  script:
    - yarn config set cache-folder .yarn
    - yarn
    - npm run lint

build:
  image: node:latest
  stage: build
  cache:
    key: "v2-$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
      - .yarn/
    policy: pull
  script:
    - yarn config set cache-folder .yarn
    - yarn
    - npm run build
  artifacts:
    expire_in: 3 days
    paths:
      - dist
  except:
    - live

deploy_master:
  stage: deploy
  script:
    - curl -X POST -d '' https://api.netlify.com/build_hooks/$NETLIFY_MASTER
  only:
    - master
