dist: trusty
sudo: false
language: node_js
cache: yarn
node_js:
  - "lts/*"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: yarn lint
after_script: greenkeeper-lockfile-upload
