dist: trusty
sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js:
  - "lts/*"
before_script:
  - rm yarn.lock
script:
  - npm run lint
  - npm run build
  - if [ ! -d dist/ ]; then exit 1; fi
