dist: trusty
sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js:
  - "lts/*"
before_install:
  - if [ -f yarn.lock ]; then rm yarn.lock; fi
script:
  - yarn lint
  - yarn build
  - if [ ! -d dist/ ]; then exit 1; fi
